### ISSUE TITLE
Module Target

### ISSUE THREAD

**Issue by guybedford** [binast/ecmascript-binary-ast#31]
There seems to be very little mention of modules in this spec and issue queue - I assume a ECMAScript Module target will be supported? Ideally this should likely be the primary use case here.

**Comment by Yoric** [comment]
As a general principle, yes, we very much want to support modules. Now, we're trying to consolidate some simpler use cases first, before moving to modules.

**Comment by guybedford** [comment]
Thanks for the update here, and glad to know that my mentions of modules in other issues are not completely off topic then!

It would still be nice to see the target mentioned in the overview.
