### ISSUE TITLE
Why feature post-default cases with `SwitchStatementWithDefault`?

### ISSUE THREAD

**Issue by isiahmeadows** [binast/ecmascript-binary-ast#39]
Semantically, the labels are meaningless after parsing, so why include them as part of the AST?

In case you're wondering what precedent there is for just ignoring the extra `case` labels:

- [ESTree](https://github.com/estree/estree/blob/master/es5.md#switchstatement)
- [Babel](https://github.com/babel/babel/blob/master/packages/babel-parser/ast/spec.md#switchstatement)
- [UglifyJS](http://lisperator.net/uglifyjs/ast) just treats them all as one and the same, making no distinction between `case` and `default`. (The minifier still strips them as dead code, however.)

**Comment by bakkot** [comment]
> Semantically, the labels are meaningless after parsing

Not sure what this means. The obvious interpretation is false: for example,

```js
switch (0) {
  default: break;
  case console.log(42):
}
```
will print `42`. Contrast 

```js
switch (0) {
  case 0:
  default: break;
  case console.log(42):
}
```
which has no effects.

Similarly,

```js
switch (0) {
  case -1: console.log(-1); break;
  default: console.log('default'); break;
  case 1: console.log(1); break;
  case 0: console.log(0); break;
  case 2: console.log(2); break;
}
```
will print `0`.

See step 9 of the third item under [CaseBlockEvaluation](https://tc39.github.io/ecma262/#sec-runtime-semantics-caseblockevaluation) (the `CaseBlock : { CaseClauses DefaultClause CaseClauses }` production).

**Comment by isiahmeadows** [comment]
Oh, then on that note, nevermind.
